### ISSUE TITLE
`pygeos` installed with pip on macos conflicts with numpy 2

### ISSUE THREAD

**Issue by gregory-halverson-jpl** [python-rasters/rasters#13]
```
❯ ipython                                                                                                                                                                        (pygeos) 
Python 3.11.10 | packaged by conda-forge | (main, Sep 10 2024, 10:57:35) [Clang 17.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.27.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pygeos

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/homebrew/Caskroom/miniforge/base/envs/pygeos/bin/ipython", line 10, in <module>
    sys.exit(start_ipython())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pygeos/lib/python3.11/site-packages/IPython/__init__.py", line 130, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pygeos/lib/python3.11/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pygeos/lib/python3.11/site-packages/IPython/terminal/ipapp.py", line 317, in start
    self.shell.mainloop()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pygeos/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py", line 917, in mainloop
    self.interact()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pygeos/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py", line 910, in interact
    self.run_cell(code, store_history=True)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pygeos/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pygeos/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pygeos/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pygeos/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pygeos/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pygeos/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-212f7c7fc761>", line 1, in <module>
    import pygeos
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pygeos/lib/python3.11/site-packages/pygeos/__init__.py", line 1, in <module>
    from .lib import GEOSException  # NOQA
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: _ARRAY_API not found
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import pygeos

File /opt/homebrew/Caskroom/miniforge/base/envs/pygeos/lib/python3.11/site-packages/pygeos/__init__.py:1
----> 1 from .lib import GEOSException  # NOQA
      2 from .lib import Geometry  # NOQA
      3 from .lib import geos_version, geos_version_string  # NOQA

ImportError: numpy.core.multiarray failed to import

In [2]:
```

**Comment by gregory-halverson-jpl** [comment]
`pygeos` is working when installed with `mamba`:
```
mamba install pygeos
```

**Comment by gregory-halverson** [comment]
`pygeos` has been replaces with `shapely`
